//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class afericao_pressao_arterial
    {
        public int apa_id_afericao { get; set; }
        public Nullable<int> apa_id_crianca { get; set; }
        public Nullable<System.DateTime> apa_dt_data { get; set; }
        public Nullable<int> apa_nr_idade { get; set; }
        public Nullable<int> apa_nr_pa_sistolica { get; set; }
        public Nullable<int> apa_nr_pa_distolica { get; set; }
        public string apa_ds_observacao { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
