//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class alimentacao_crianca
    {
        public int alc_id_crianca { get; set; }
        public int alc_id_alimentacao { get; set; }
        public Nullable<System.DateTime> alc_dt_data { get; set; }
        public string alc_ds_alimentacao { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
