//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class dados_alta
    {
        public int dda_id_alta { get; set; }
        public int ddai_id_crianca { get; set; }
        public Nullable<System.DateTime> dda_dt_alta { get; set; }
        public Nullable<float> dda_nr_peso { get; set; }
        public string dda_ds_alimentacao { get; set; }
        public string dda_ds_anotacoes { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
