//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class exames_triagem_neonatal
    {
        public int etn_id_exames_neonatal { get; set; }
        public int etni_id_crianca { get; set; }
        public string etn_st_manobra_ortolani { get; set; }
        public string etn_ds_conduta_ortolani { get; set; }
        public string etn_st_teste_reflexo_vermelho { get; set; }
        public string etn_ds_conduta_reflexo_vermelho { get; set; }
        public string etn_st_teste_pezinho { get; set; }
        public Nullable<System.DateTime> etn_dt_teste_pezinho { get; set; }
        public string etn_st_fenilcitonuria { get; set; }
        public string etn_st_hipotireoidismo { get; set; }
        public string etn_st_anemia_falciforme { get; set; }
        public string etn_ds_outros { get; set; }
        public string etn_st_triagem_auditiva { get; set; }
        public Nullable<System.DateTime> etn_dt_triagem_auditiva { get; set; }
        public string etn_ds_testes_realizados_auditivos { get; set; }
        public string etn_st_resultado_od { get; set; }
        public string etn_st_resultado_oe { get; set; }
        public string etn_ds_conduta_triagem_auditiva { get; set; }
        public string etn_st_reteste { get; set; }
        public Nullable<System.DateTime> etn_dt_reteste { get; set; }
        public string etn_ds_testes_realizados_auditivos_reteste { get; set; }
        public string etn_st_resultado_od_reteste { get; set; }
        public string etn_st_resultado_oe_reteste { get; set; }
        public string etn_ds_conduta_triagem_auditiva_reteste { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
