//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class intercorrencias
    {
        public int int_id_crianca { get; set; }
        public int int_id_intercorrencia { get; set; }
        public Nullable<System.DateTime> int_dt_data { get; set; }
        public string int_ds_intercorrencia { get; set; }
        public string int_ds_observacoes { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
