//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcador_desenvolvimento_crianca
    {
        public int mdc_id_marcador_crianca { get; set; }
        public int mdc_id_marcador { get; set; }
        public int mdc_id_crianca { get; set; }
        public Nullable<int> mdc_nr_idade { get; set; }
        public string mdc_ds_status { get; set; }
    
        public virtual crianca crianca { get; set; }
        public virtual marcador_desenvolvimento marcador_desenvolvimento { get; set; }
    }
}
