//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcador_desenvolvimento
    {
        public marcador_desenvolvimento()
        {
            this.marcador_desenvolvimento_crianca = new HashSet<marcador_desenvolvimento_crianca>();
        }
    
        public int mdv_id_marcador { get; set; }
        public string mdv_ds_marcador { get; set; }
        public string mdv_ds_como_investigar { get; set; }
    
        public virtual ICollection<marcador_desenvolvimento_crianca> marcador_desenvolvimento_crianca { get; set; }
    }
}
