//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class nascimento
    {
        public int nas_id_nascimento { get; set; }
        public int nas_id_crianca { get; set; }
        public Nullable<System.DateTime> nas_dt_nascimento { get; set; }
        public string nas_ds_maternidade { get; set; }
        public int nas_id_municipio { get; set; }
        public Nullable<float> nas_nr_peso { get; set; }
        public Nullable<float> nas_nr_comprimento { get; set; }
        public Nullable<float> nas_nr_perimetro_encefalico { get; set; }
        public string nas_ds_sexo { get; set; }
        public string nas_ds_apagar_1_min { get; set; }
        public string nas_ds_apagar_5_min { get; set; }
        public Nullable<int> nas_nr_idade_gestacional_semanas { get; set; }
        public Nullable<int> nas_nr_idade_gestacional_dias { get; set; }
        public string nas_ds_metodo_avaliacao_ig { get; set; }
        public string nas_ds_tipo_sanguineo { get; set; }
        public string nas_ds_tipo_sanguineo_mae { get; set; }
        public string nas_st_aleitamento_primeira_hora { get; set; }
        public string nas_ds_profissional_assistiu { get; set; }
        public string nas_nr_hora_nascimento { get; set; }
    
        public virtual crianca crianca { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
