//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class outras_observacoes
    {
        public int obs_id_crianca { get; set; }
        public int obs_id_observacoes { get; set; }
        public Nullable<System.DateTime> obs_dt_data { get; set; }
        public string obs_ds_anotacao { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
