//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class parto
    {
        public int par_id_parto { get; set; }
        public int par_id_crianca { get; set; }
        public string par_ds_local { get; set; }
        public string par_tp_parto { get; set; }
        public string par_ds_indicacao { get; set; }
        public string par_st_z21_status { get; set; }
        public Nullable<int> par_nr_z21_periodo { get; set; }
        public string par_st_a53_status { get; set; }
        public Nullable<int> par_st_a53_periodo { get; set; }
        public string par_st_megadose_vitamina_a { get; set; }
        public string par_ds_intercorrencias_clinicas { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
