//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public perfil()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int per_id_perfil { get; set; }
        public string per_ds_perfil { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
