//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class saude_ocular
    {
        public int sao_id_crianca { get; set; }
        public int sao_id_saude_ocular { get; set; }
        public Nullable<int> sao_nr_periodo { get; set; }
        public string sao_st_resultado_tav { get; set; }
        public byte[] sao_st_consulta_oftamologica { get; set; }
        public byte[] sao_st_disturbio_visual { get; set; }
        public byte[] sao_st_prescricao_oculos { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
