//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplementacao_vitamina_a
    {
        public int sva_id_crianca { get; set; }
        public int sva_id_suplementacao_vitamina_a { get; set; }
        public Nullable<System.DateTime> sva_dt_data { get; set; }
        public string sva_ds_local { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
