//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplementacao_ferro
    {
        public int suf_id_crianca { get; set; }
        public int suf_id_suplementacao_ferro { get; set; }
        public Nullable<System.DateTime> suf_dt_suplementacao { get; set; }
        public string suf_ds_local { get; set; }
    
        public virtual crianca crianca { get; set; }
    }
}
