//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.crianca = new HashSet<crianca>();
            this.crianca_usuario = new HashSet<crianca_usuario>();
        }
    
        public int usu_id_usuario { get; set; }
        public string usu_nr_cpf { get; set; }
        public string usu_ds_nome { get; set; }
        public string usu_nr_telefone { get; set; }
        public string usu_ds_email { get; set; }
        public string usu_ds_senha { get; set; }
        public int usu_id_perfil { get; set; }
    
        public virtual ICollection<crianca> crianca { get; set; }
        public virtual ICollection<crianca_usuario> crianca_usuario { get; set; }
        public virtual perfil perfil { get; set; }
    }
}
