//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacina
    {
        public vacina()
        {
            this.vacinas_crianca = new HashSet<vacinas_crianca>();
        }
    
        public int vac_id_vacina { get; set; }
        public string vac_ds_vacina { get; set; }
    
        public virtual ICollection<vacinas_crianca> vacinas_crianca { get; set; }
    }
}
