//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSC.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacinas_crianca
    {
        public int vcc_id_vacina_crianca { get; set; }
        public int vcc_id_vacina { get; set; }
        public int vcc_id_crianca { get; set; }
        public Nullable<System.DateTime> vcc_dt_data { get; set; }
        public string vcc_nr_dose { get; set; }
        public string vcc_nr_lote { get; set; }
        public string vcc_ds_unidade { get; set; }
    
        public virtual crianca crianca { get; set; }
        public virtual vacina vacina { get; set; }
    }
}
